coverage:
  precision: 2
  round: down
  range: 90...90
  status:
    patch:
      default:
        target: 90%
        threshold: 1%
    project:
      default:
        target: 90%
        threshold: 1%

comment: false
