name: Main

on:
  push:
    branches: ["*"] # Run only when push to branches (not tags).
    paths-ignore:
      - "codeforlife/version.py"
      - "**/*.md"
      - ".vscode/**"
      - ".*"
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: [3.8]
  #   steps:
  #     - uses: ocadotechnology/codeforlife-workspace/.github/actions/python/test@actions # TODO: use @main
  #       with:
  #         python-version: ${{ matrix.python-version }}

  docs:
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      - uses: ocadotechnology/codeforlife-workspace/.github/actions/python/docs@actions # TODO: use @main

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [docs]
    if: github.ref_name == 'main'
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🛠 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-semantic-release~=7.33

      - name: ⚙️ Configure Git
        run: |
          git config --local user.name cfl-bot
          git config --local user.email codeforlife-bot@ocado.com

      - name: 🚀 Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: semantic-release publish --verbosity=INFO
