name: Main

on:
  push:
    branches: ["*"] # Run only when push to branches (not tags).
    paths-ignore:
      - "codeforlife/version.py"
      - "**/*.md"
      - ".vscode/**"
      - ".*"
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-python-code.yaml@main

  docs:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: ocadotechnology/codeforlife-workspace/.github/actions/python/docs@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [docs]
    if: github.ref_name == 'main'
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🛠 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-semantic-release~=7.33

      - uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

      - name: 🚀 Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: semantic-release publish --verbosity=INFO
