name: Main

on:
  push:
    branches: ["*"] # Run only when push to branches (not tags).
    paths-ignore:
      - "codeforlife/version.py"
      - "**/*.md"
      - ".vscode/**"
      - ".*"
  workflow_dispatch:

jobs:
  test:
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-python-code.yaml@main
    with:
      # Cannot be set with an env var. Value must match in the release job.
      python-version: 3.8

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref_name == 'main'
    env:
      # Value must match in the test job.
      PYTHON_VERSION: 3.8
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CFL_BOT_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🛠 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-semantic-release~=7.33

      - name: 🤖 Set up cfl-bot as Git User
        uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

      - name: 🚀 Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.CFL_BOT_GITHUB_TOKEN }}
        run: semantic-release publish --verbosity=INFO
