name: Main

on:
  push:
    branches: ["*"] # Run only when push to branches (not tags).
    paths-ignore:
      - "codeforlife/version.py"
      - "**/*.md"
      - ".vscode/**"
      - ".*"
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      python-version:  3.8

  test:
    needs: [config]
    uses: ocadotechnology/codeforlife-workspace/.github/workflows/test-python-code.yaml@main
    with:
      python-version: ${{ needs.config.outputs.python-version }}

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: [config, test]
    if: github.ref_name == 'main'
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CFL_BOT_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🐍 Set up Python ${{ needs.config.outputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.config.outputs.python-version }}

      - name: 🛠 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-semantic-release~=7.33

      - name: 🤖 Set up cfl-bot as Git User
        uses: ocadotechnology/codeforlife-workspace/.github/actions/git/setup-bot@main

      - name: 🚀 Publish Semantic Release
        env:
          GH_TOKEN: ${{ secrets.CFL_BOT_GITHUB_TOKEN }}
        run: semantic-release publish --verbosity=INFO
